### ISSUE TITLE
InvalidOperationException

### ISSUE THREAD

**Issue by sommmen** [StackExchange/StackExchange.Utils#23]
Hiya,

I'm getting the following error:

`Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.`

```
   at System.ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported()
   at System.Collections.Generic.HashSet`1.FindItemIndex(T item)
   at System.Collections.Generic.HashSet`1.Contains(T item)
   at StackExchange.Utils.SubstitutionHelper.CycleDetector.Contains(String key) in D:\a\StackExchange.Utils\StackExchange.Utils\src\StackExchange.Utils.Configuration\SubstitutionHelper.cs:line 146
   at StackExchange.Utils.SubstitutionHelper.ReplaceSubstitutionPlaceholders(String key, String value, IConfiguration substitutions, Func`1 cycleDetectorFactory) in D:\a\StackExchange.Utils\StackExchange.Utils\src\StackExchange.Utils.Configuration\SubstitutionHelper.cs:line 100
   at StackExchange.Utils.SubstitutionHelper.TryGetWithSubstitution(IConfiguration configuration, String key, String& value, IConfiguration substitutions) in D:\a\StackExchange.Utils\StackExchange.Utils\src\StackExchange.Utils.Configuration\SubstitutionHelper.cs:line 48
   at StackExchange.Utils.SubstitutingConfigurationProvider.TryGet(String key, String& value) in D:\a\StackExchange.Utils\StackExchange.Utils\src\StackExchange.Utils.Configuration\SubstitutingConfigurationProvider.cs:line 18
   at Microsoft.Extensions.Configuration.ConfigurationRoot.get_Item(String key)
   at Microsoft.Extensions.Configuration.ConfigurationSection.get_Item(String key)
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(IConfiguration configuration, String name)
   at OPG.DAL.Factories.WpRepositoryFactory.GetConnectionString(WpShop shop) in C:\Repos\REDACTED\.cs:line 41
```

I'm using hangfire with backgroundtasks - so it could be possible that some parallelization is going on.

``` csharp
        public static IConfigurationBuilder ConfigureOpgAppSettings(this IConfigurationBuilder builder) =>
            builder
                .WithPrefix("REDACTED",
                    c => c.AddJsonFile("REDACTED.json", true)
                        .AddJsonFile(Environment.ExpandEnvironmentVariables("REDACTED.json"), true)
                        .AddJsonFile($"{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")}.REDACTED.json", true)
                ).WithSubstitution(x =>
                    x.AddJsonFile("appsettings.json")
                        .AddJsonFile($"appsettings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")}.json", true));
    }
```

Am i doing something wrong or can someone point me in the right direction?

I'm using net core 3.1. (I'm referencing the 3.1 library project from a 5.0 console project)

Package version:
`StackExchange.Utils.Configuration              0.1.5       0.1.5   `

**Comment by deanward81** [comment]
I’ve seen this in the wild too but have been having trouble reproducing it. I’ll keep at it but if you have a concrete repro that would certainly help things along!

**Comment by sommmen** [comment]
> I’ve seen this in the wild too but have been having trouble reproducing it. I’ll keep at it but if you have a concrete repro that would certainly help things along!

Well reproducing concurrency issues are always hard so no...

Anyhow i worked around this by applying locks in some parts and by moving some things to stop concurrent usage like:

e.g.

``` csharp
opt.UseSqlServer(_defaultConnectionString, o =>
{
    o.EnableRetryOnFailure(3);
    o.CommandTimeout((int)TimeSpan.FromMinutes(10).TotalSeconds);
});
```
`_defaultConnectionString` used to be just `_configuration.GetConnectionString("DefaultConnection")`. or something along that lines - i remember applying that fix.

Anyways creating dbcontext (which'd happen concurrently) would cause refetching the connection string which would cause this exception. The behaviour seemd to be quite consistend, so i'm guessing just add 2 json files, with substitution and create a bunch of tasks that would access the configuration and the bug should pop up?

Anyhow the cycle detector just needs some thread safety it seems anyways.

**Comment by sommmen** [comment]
Hm - weird the CycleDetector is AsyncLocal so pretty weird that the hashset would get concurrent operations..

https://github.com/StackExchange/StackExchange.Utils/blob/5a3ed9942079600eab4971f198e046b7dd4ec3d8/src/StackExchange.Utils.Configuration/SubstitutionHelper.cs

**Comment by deanward81** [comment]
@sommmen that’s my confusion, there’s definitely a case where an `AsyncLocal` is being shared by two or more threads downstream (hence the exception). I’ll dig in a bit more, I have an idea on how to repro this, just gotta try it

**Comment by sommmen** [comment]
@NickCraver @deanward81 

Hiya - is this fix released yet or?

![image](https://user-images.githubusercontent.com/8641495/158834564-fddf6350-815c-42a8-ae14-79047fd27893.png)

**Comment by deanward81** [comment]
@sommmen apologies, this week has been hectic - I’ll get it to NuGet tomorrow

**Comment by sommmen** [comment]
> @sommmen apologies, this week has been hectic - I’ll get it to NuGet tomorrow

Sure thing no hurry I got this patched anyways. And don't forget to relax for a bit of mindfulness

**Comment by dev-marcel** [comment]
Also waiting on this fix, hope it gets released soon. Awesome library btw.

**Comment by sommmen** [comment]
> @sommmen apologies, this week has been hectic - I’ll get it to NuGet tomorrow

@deanward81 Just another reminder to release a new nuget package ^^ :).

**Comment by deanward81** [comment]
@sommmen @dev-marcel sorry, this had completely slipped my mind; [0.1.7 is now up on NuGet](https://www.nuget.org/packages/StackExchange.Utils.Configuration/0.1.7) - apologies for the delay!!

**Comment by PH-Lars** [comment]
@deanward81 Hi, I'm on 0.1.7 and still getting this issue. Mainly when using it with Hangfire (same process) with multiple jobs starting up at the same time.

Not sure if its due to the cycledetector being static or, the release is from march but if I check the StackExchange.Utils.Configuration.dll from 0.1.7 it says it was mutated on 24-02-2022 19:56. 

Are you sure the nuget package 0.1.7 contains the new build?
- 23-09-2022- Just to confirm, a custom build results in the fix working as intended. Looks to me like the 0.1.7 is indeed missing the latest build.

**Comment by deanward81** [comment]
@PH-Lars you are absolutely correct, last action run screwed up and I thought that this was released already. Really sorry for the inconvenience, I'm re-building and will release as soon as it's done.

**Comment by deanward81** [comment]
@PH-Lars (and @sommmen , @dev-marcel ) - version 0.1.12 with the fix is up on NuGet: https://www.nuget.org/packages/StackExchange.Utils.Configuration/0.1.12. I've downloaded the package and validated that it actually contains what you'd expect :). Sorry about that!

**Comment by PH-Lars** [comment]
@deanward81 Thanks for the quick response and release!
